syntax = "proto3";
package Protocol;

option csharp_namespace = "Google.Protobuf.Protocol";

enum MsgId 
{
	C_JWT_LOGIN_REQUEST = 0;
	S_JWT_LOGIN_REPLY = 1;
	C_CREATE_CHARACTER_REQUEST = 2;
	S_CREATE_CHARACTER_REPLY = 3;
	C_CHARACTER_LIST_REQUEST = 4;
	S_CHARACTER_LIST_REPLY = 5;
	C_DELETE_CHARACTER_REQUEST = 6;
	S_DELETE_CHARACTER_REPLY = 7;
	C_ENTER_GAME = 8;
	S_ENTER_GAME = 9;
	S_PLAYER_LIST = 10;
	S_BROADCAST_PLAYER_ENTER = 11;
	C_LEAVE_GAME = 12;
	S_LEAVE_GAME = 13;
	S_BROADCAST_PLAYER_LEAVE = 14;
	C_PLAYER_MOVE_REQUEST = 15;
	S_PLAYER_MOVE_REPLY = 16;
	S_BROADCAST_PLAYER_MOVE = 17;
	S_CHANGE_ROOM_BEGIN = 18;
	C_CHANGE_ROOM_READY = 19;
	S_CHANGE_ROOM_COMMIT = 20;
	S_SPAWN_MONSTER = 21;
	S_DESPAWN_MONSTER = 22;
	S_BROADCAST_MONSTER_MOVE = 23;
	S_BROADCAST_MONSTER_ATTACK = 24;
	S_BROADCAST_MONSTER_DEATH = 25;
	C_PLAYER_ATTACK_REQUEST = 26;
	S_BROADCAST_PLAYER_ATTACK = 27;
	C_INVENTORY_REQUEST = 28;
	S_INVENTORY_REPLY = 29;
	C_ITEM_USE_REQUEST = 30;
	S_ITEM_USE_REPLY = 31;
	S_INVENTORY_UPDATE = 32;
	S_SYSTEM_MESSAGE = 33;
	S_MONSTER_LIST = 34;
	C_NPC_INTERACT_REQUEST = 35;
	S_NPC_INTERACT_REPLY = 36;
	S_NPC_SHOP_OPEN = 37;
	C_NPC_SHOP_BUY_REQUEST = 38;
	S_NPC_SHOP_BUY_REPLY = 39;
	S_PLAYER_STAT = 40;
	S_BROADCAST_PLAYER_TRY_ATTACK = 41;
	S_BROADCAST_PLAYER_HP_CHANGED = 42;
	S_BROADCAST_PLAYER_DEATH = 43;
	C_PLAYER_CHAT = 44;
	S_BROADCAST_PLAYER_CHAT = 45;
	C_GIVE_ITEM_REQUEST = 46;
	S_GIVE_ITEM_REPLY = 47;
}

// 클라 -> 게임 서버 jwt 로그인 인증 (0)
message C_JwtLoginRequest 
{
	string accessToken = 1; 
}

// 게임서버 -> 클라 jwt 검증 (1)
message S_JwtLoginReply
{
	ELoginResult result = 1;
}

// (2)
message C_CreateCharacterRequest
{
	string username = 1; // 캐릭터 이름 한글만 가능 2~6자
	EGender gender = 2; 
	ERegion region = 3;
}

// (3)
message S_CreateCharacterReply
{
	bool success = 1;
	string detail = 2; // 실패 시 에러 메시지
}

// (4)
message C_CharacterListRequest
{

}

// (5)
message S_CharacterListReply
{
	repeated CharacterSummaryInfo characters = 1;
}

// (6)
message C_DeleteCharacterRequest
{
	int32 characterIndex = 1;
}

// (7)
message S_DeleteCharacterReply
{
	bool success = 1;
	string errorMessage = 2;
}

// (8)
message C_EnterGame
{
	int32 playerIndex = 1;
}

// (9)
message S_EnterGame
{
	int32 success = 1;
}

// (10)
message S_PlayerList
{
	int32 myPlayerId = 1;
	int32 mapId = 2;
	repeated PlayerInfo players = 3;
}

// (11)
message S_BroadcastPlayerEnter
{
	PlayerInfo player = 1;
}

// (12)
message C_LeaveGame
{
	ELeaveReason reason = 1;
}

// (13)
message S_LeaveGame
{
	bool success = 1;
	string detail = 2;
}

// (14)
message S_BroadcastPlayerLeave
{
	int32 playerId = 1;
	ELeaveReason reason = 2;
}
// (15)
message C_PlayerMoveRequest
{
	Vector2Info clickWorldPos = 1;
}

// (16)
message S_PlayerMoveReply
{
	int32 playerId = 1;
	int32 clientSeq = 2;
	EMoveResult result = 3;
	int32 tick = 4;
	Vector2Info newPos = 5;
	EDirection direction = 6;
}

// (17)
message S_BroadcastPlayerMove
{
	int32 tick = 1;
	repeated PlayerMoveInfo playerMoves = 2; // 변경된 플레이어만 담을 것
}

// (18) 서버가 시작 알림 (클라 입력 잠금, 로딩 UI)
message S_ChangeRoomBegin {
  int32 transitionId = 1;
  int32 mapId        = 2;
}

// (19) 클라가 준비 완료 통보(리소스/타일맵 로드 완료)
message C_ChangeRoomReady {
  int32 transitionId = 1;
}

// (20) 서버가 최종 스폰 좌표/스냅샷 확정
message S_ChangeRoomCommit {
  int32 transitionId = 1;
  int32 mapId = 2;
  // Snapshot은 OnEnter에서 PlayerList보내는것으로 대신함
}

// (21) 서버 -> 클라 : 몬스터 스폰 알림
message S_SpawnMonster {
	MonsterInfo monster = 1;
}

// (22) 서버 -> 클라 몬스터 디스폰(제거) 알림 
message S_DespawnMonster {
	int32 monsterId = 1;
	EDespawnReason reason = 2; // 정수 코드 EDespawnReason 참고
}

// (23) 서버 -> 클라 : 몬스터 이동 브로드 캐스트
message S_BroadcastMonsterMove {
	int32 monsterId = 1;
	int32 x			= 2; // 이동 위치 X
	int32 y			= 3; // 이동 위치 Y
	EDirection dir	= 4; // 방향
}

// (24) 서버 -> 클라 : 몬스터 공격 브로드 캐스트
message S_BroadcastMonsterAttack {
	int32 monsterId = 1;
	int32 targetPid = 2; // 공격 대상 Player Id
	int32 damage = 3;
	int32 hpAfter = 4;
}

// (25) 서버 -> 클라 : 몬스터 사망 브로드 캐스트
message S_BroadcastMonsterDeath {
	int32 monsterId = 1;
}
// (26) 클라 -> 서버 : 플레이어 공격 서버 전송
message C_PlayerAttackRequest {

}

// (27) 서버 -> 클라 : 플레이어 공격 브로드 캐스트
message S_BroadcastPlayerAttack {
	int32 playerId = 1;
	int32 targetId = 2;
	int32 damage = 3;
	int32 hpAfter = 4;
}
// (28) 클라 -> 서버 : 인벤토리 조회 요청
message C_InventoryRequest {

}

// (29) 서버 -> 클라 : 인벤토리 응답
message S_InventoryReply {
	repeated InventorySlotInfo slots = 1;
}

// (30) 클라 -> 서버 : 아이템 사용 요청
message C_ItemUseRequest {
	int32 slotIndex = 1;
}

// (31) 서버 -> 클라 : 아이템 사용 응답
message S_ItemUseReply {
	bool success = 1;
	string errorMessage = 2;
}

// (32) 서버 -> 클라 : 인벤토리 업데이트 브로드캐스트
message S_InventoryUpdate {
	repeated InventorySlotInfo changedSlots = 1;
}

// (33) 서버 -> 클라 : 시스템 메시지 (드랍,.. 등등)
message S_SystemMessage {
	string message = 1;
	EMessageType type = 2;
}

// (34) 서버 -> 클라 :  몬스터 리스트 스냅샷
message S_MonsterList
{
	int32 mapId = 1;
	repeated MonsterInfo monsters = 2;
}

// (35) 클라 -> 서버 : Npc 정보 요청
message C_NpcInteractRequest {
	
}

// (36) 서버 -> 클라 : Npc 정보 응답
message S_NpcInteractReply { 
	repeated string dialogs = 1;
	int32 interactionType = 2; // 0=Talk, 1=Shop, 2=Quest
}

// (37) 서버 -> 클라 : 상점 정보 전달
message S_NpcShopOpen {
	int32 npcId = 1;
	repeated ShopItemInfo items = 2;
}

// (38) 클라 -> 서버 : 상점 아이템 구매 요청
message C_NpcShopBuyRequest {
	int32 npcId = 1;
	int32 itemId = 2;
	int32 quantity = 3;
}

// (39) 서버 -> 클라 : 상점 아이템 구매 요청 응답
message S_NpcShopBuyReply {
	bool success = 1;
	string detail = 2;
}

// 40 (서버) -> 클라 : 플레이어 스텟 전달
message S_PlayerStat {
	PlayerStatInfo statInfo = 1;
}

// (41) 서버 -> 클라 : 플레이어 공격 시도 브로드캐스트
message S_BroadcastPlayerTryAttack 
{
	int32 playerId = 1;
}

// (42) 서버 -> 클라 : S_BroadcastPlayerHpChanged

message S_BroadcastPlayerHpChanged
{
	int32 playerId = 1;
	int32 hp = 2;
	int32 maxHp = 3;
}
// (43) 서버 -> 클라 : S_BroadcastPlayerDeath
message S_BroadcastPlayerDeath
{
	int32 playerId = 1;
	int32 killerMonsterId = 2;
}

// (44) 클라 -> 서버 : C_PlayerChat 채팅 송신
message C_PlayerChat
{
	PlayerChatInfo playerChatInfo = 1;
}

// (45) 서버 -> 클라 : S_BroadcastPlayerChat : Room-Tick마다 Server가 Player에게 모아둔 채팅 송신
message S_BroadcastPlayerChat
{
	repeated PlayerChatInfo playerChatInfos = 1;
}

// (46) 클라 -> 서버 : 테스트용 아이템 지급 요청
message C_GiveItemRequest
{
	int32 itemId = 1;
	int32 count = 2;
}

// (47) 서버 -> 클라 : 아이템 지급 결과 응답
message S_GiveItemReply
{
	bool success = 1;
	string errorMessage = 2;
	InventorySlotInfo addedSlot = 3;
}

enum ELoginResult
{
    SUCCESS = 0;
    INVALID_TOKEN = 1;
    TOKEN_EXPIRED = 2;
    SERVER_ERROR = 3;
}

enum EGender 
{
	GENDER_NONE = 0;
	GENDER_MALE = 1;
	GENDER_FEMALE = 2;
}

enum ERegion 
{
    REGION_NONE = 0;
    REGION_GO = 1;
    REGION_BACK = 2;
}

enum EDirection
{
	DIR_UP = 0;
	DIR_DOWN = 1;
	DIR_LEFT = 2;
	DIR_RIGHT = 3;
}

enum ELeaveReason
{
	LEAVE_UNKNOWN = 0;
	LEAVE_LOGOUT = 1; // 로그아웃 -> Jwt 로그인 인증 상태로 (세션 초기화)
	LEAVE_CHANGE_ROOM = 2; // 룸 이동
	LEAVE_CHANGE_CHARACTER = 3; // 캐릭터 변경 -> 세션은 유지하고 캐릭터 선택으로 변경
	LEAVE_DISCONNECT = 4; // 네트워크 끊김
}

enum EMoveResult
{
	MOVE_UNKNOWN = 0;
	MOVE_OK = 1;
	MOVE_DIR = 2;
	MOVE_COOLDOWN = 3;
	MOVE_BLOCKED = 4; 
}

enum EEnterReason
{
	ENTER_UNKNOWN = 0;
	ENTER_LOGIN = 1;
	ENTER_CHANGE_ROOM = 2;
}

enum EDespawnReason
{
	DESPAWN_UNKNOWN = 0;
	DESPAWN_KILLED = 1;
}

enum EItemType
{
	ITEM_TYPE_UNKNOWN = 0;
	ITEM_TYPE_CONSUMABLE = 1;   // 소비형 아이템 (포션 등)
	ITEM_TYPE_EQUIPMENT = 2;    // 장비 아이템
	ITEM_TYPE_QUEST = 3;        // 퀘스트 아이템
	ITEM_TYPE_MISC = 4;         // 기타 아이템
}

enum EMessageType
{
	MESSAGE_INFO = 0;
	MESSAGE_WARNING = 1;
	MESSAGE_ERROR = 2;
	MESSAGE_DROP_FAILED = 3;
}

enum EChatType
{
	CHAT_ROOM = 0;
	CHAT_ALL = 1;
}
message Vector2Info
{
	int32 x = 1;
	int32 y = 2;
}

message PlayerMoveInfo
{
	int32 playerId = 1;
	EDirection direction = 2; 
	Vector2Info newPos = 3;
	EMoveResult result = 4;
}

message CharacterSummaryInfo
{
	string username = 1;
	int32 level = 2;
	EGender gender = 3;
	ERegion region = 4;
}

message PlayerInfo
{
	int32 id = 1;
	string username = 2;

	Vector2Info pos = 3;
	EDirection direction = 4;
}

message InventorySlotInfo
{
	int32 slotIndex = 1;
	int32 itemId = 2;
	int32 count = 3;
	bool isQuickslot = 4;
}

message MonsterInfo
{
	int32 monsterId = 1; // Entity Unique id
	int32 monsterTypeId = 2; // Monster Type (Template or Resources Id)
	Vector2Info pos = 3;
	EDirection direction = 4;
}

message ShopItemInfo
{
	int32 itemId = 1;
	int32 quantity = 2; // 수량
	int32 price = 3;	// 1개당 가격
}

message PlayerStatInfo
{
	int32 maxHp = 1;
	int32 hp = 2;
	int32 curExp = 3;
	int32 maxExp = 4;
	int32 level = 5;
	int32 money = 6;
}

message PlayerChatInfo
{
	oneof playerIncluded {
		bool NonePlayer = 1; // Client -> Server로 보낼떄
		int32 playerId = 2; // Server -> Client로 보낼때
	}
	string message = 3;
	EChatType chatType = 4; 
}