// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum ELoginResult : int {
  SUCCESS = 0,
  INVALID_TOKEN = 1,
  TOKEN_EXPIRED = 2,
  SERVER_ERROR = 3,
  ELoginResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ELoginResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ELoginResult_IsValid(int value);
constexpr ELoginResult ELoginResult_MIN = SUCCESS;
constexpr ELoginResult ELoginResult_MAX = SERVER_ERROR;
constexpr int ELoginResult_ARRAYSIZE = ELoginResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ELoginResult_descriptor();
template<typename T>
inline const std::string& ELoginResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ELoginResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ELoginResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ELoginResult_descriptor(), enum_t_value);
}
inline bool ELoginResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ELoginResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ELoginResult>(
    ELoginResult_descriptor(), name, value);
}
enum EGender : int {
  GENDER_NONE = 0,
  GENDER_MALE = 1,
  GENDER_FEMAIL = 2,
  EGender_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EGender_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EGender_IsValid(int value);
constexpr EGender EGender_MIN = GENDER_NONE;
constexpr EGender EGender_MAX = GENDER_FEMAIL;
constexpr int EGender_ARRAYSIZE = EGender_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGender_descriptor();
template<typename T>
inline const std::string& EGender_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EGender>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EGender_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EGender_descriptor(), enum_t_value);
}
inline bool EGender_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EGender* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EGender>(
    EGender_descriptor(), name, value);
}
enum ERegion : int {
  REGION_NONE = 0,
  REGION_GO = 1,
  REGION_BACK = 2,
  ERegion_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ERegion_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ERegion_IsValid(int value);
constexpr ERegion ERegion_MIN = REGION_NONE;
constexpr ERegion ERegion_MAX = REGION_BACK;
constexpr int ERegion_ARRAYSIZE = ERegion_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ERegion_descriptor();
template<typename T>
inline const std::string& ERegion_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ERegion>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ERegion_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ERegion_descriptor(), enum_t_value);
}
inline bool ERegion_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ERegion* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ERegion>(
    ERegion_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::ELoginResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ELoginResult>() {
  return ::Protocol::ELoginResult_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EGender> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EGender>() {
  return ::Protocol::EGender_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ERegion> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ERegion>() {
  return ::Protocol::ERegion_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
